mutation CREATE_COMMENT($username: String, $email: String, $postId: Int, $comment: String) {
    createComment(
    input: {commentOn: $postId, content: $comment, author: $username, authorEmail: $email}
    ) {
    success
    comment {
        date
        content
        author {
        node {
            avatar {
            url
            }
            name
        }
        }
    }
    }
}