query GET_CATEGORY($id: ID!) {
    category(id: $id, idType: SLUG) {
        name
        posts {
            nodes {
                id
                slug
                title
                date
                excerpt
                featuredImage {
                    node {
                        altText
                        mediaItemUrl
                        mediaDetails {
                            height
                            width
                        }
                        srcSet
                    }
                }
                categories {
                    nodes {
                        id
                        name
                    }
                }
                commentCount
            }
        }
    }
}