query GET_CATEGORY($id: ID!, $after: String = "", $limit: Int = 10) {
    category(id: $id, idType: SLUG) {
        name
        posts(after: $after, first: $limit) {
            nodes {
                id
                slug
                title
                date
                excerpt
                featuredImage {
                    node {
                        altText
                        mediaItemUrl
                        mediaDetails {
                            height
                            width
                        }
                        srcSet
                    }
                }
                categories {
                    nodes {
                        id
                        name
                    }
                }
                commentCount
            }
            pageInfo {
                endCursor
                hasNextPage
            }
        }
    }
}