query GET_CONTENT($id: ID = "") {
  page(id: $id, idType: URI) {
    id
    title
    content
  }
  post(id: $id, idType: URI) {
    title
    databaseId
    excerpt
    date
    content
    featuredImage {
      node {
        altText
        caption
        mediaItemUrl
        mediaDetails {
          height
          width
        }
        srcSet
      }
    }
    categories {
      nodes {
        id
        name
        slug
      }
    }
    tags {
      nodes {
        id
        name
        slug
      }
    }
    author {
      node {
        avatar {
          url
        }
        name
        description
      }
    }
    commentStatus
    commentCount
    comments(where: {orderby: COMMENT_DATE, order: ASC, parentIn: "null"}) {
      nodes {
        date
        content
        author {
          node {
            avatar {
              url
            }
            name
          }
        }
        replies {
          nodes {
            date
            content
            author {
              node {
                avatar {
                  url
                }
                name
              }
            }
          }
        }
      }
    }
  }
}