query GET_POSTS($after: String = "", $limit: Int = 10) {
  posts(where: {status: PUBLISH}, after: $after, first: $limit) {
    nodes {
      id
      slug
      title
      date
      excerpt
      featuredImage {
        node {
          altText
          mediaItemUrl
          mediaDetails {
            height
            width
            sizes(include: POST_CARD) {
              height
              sourceUrl
              width
            }
          }
          srcSet
        }
      }
      categories {
        nodes {
          id
          name
          slug
        }
      }
      commentCount
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}