query Posts {
  posts(where: {status: PUBLISH}) {
    nodes {
      id
      slug
      title
      date
      excerpt
      featuredImage {
        node {
          altText
          mediaItemUrl
          mediaDetails {
            height
            width
          }
          srcSet
        }
      }
      categories {
        nodes {
          id
          name
          slug
        }
      }
      commentCount
    }
  }
}